spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: dev

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace