spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cds-server.cxfnzlz2vmbm.ap-northeast-2.rds.amazonaws.com:3306/cds_server?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: server
    password: sopt1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace